export default {
  rubro: [
    {
      id: 1,
      descripcion: "Comidas",
      porcentajeAumento: 2,
      ultimoAumento: "22/10/2022",
    },
    {
      id: 2,
      descripcion: "Bebidas",
      porcentajeAumento: 5,
      ultimoAumento: "30/10/2022",
    },
    {
      id: 3,
      descripcion: "Envasados",
      porcentajeAumento: 3,
      ultimoAumento: "17/10/2022",
    },
  ],
  marca: [
    {
      id: 1,
      nombre: "Trapiche",
      porcentajeAumento: 2,
      ultimoAumento: "22/10/2022",
    },
    {
      id: 2,
      nombre: "Cocinero",
      porcentajeAumento: 5,
      ultimoAumento: "30/10/2022",
    },
    {
      id: 3,
      nombre: "Don Silvestre",
      porcentajeAumento: 5,
      ultimoAumento: "30/10/2022",
    },
  ],
  producto: [
    {
      id: 1,
      descripcion: "Empanada de Roquefort y Jamon",
      marca: null,
      rubro: "Comidas",
      precioVenta: 150,
      precioCosto: null,
      tipoIva: "4%",
      stock: 20,
      stockMinimo: 10,
      proveedores: null,
    },
    {
      id: 2,
      descripcion: "Vino Tinto Malbec",
      marca: "Trapiche",
      rubro: "Bebidas",
      precioVenta: 1200,
      precioCosto: 700,
      tipoIva: "21%",
      stock: 5,
      stockMinimo: 2,
      proveedores: [
        { id: 1, razonSocial: "Codeana S.A", cuit: "31-35665513-7" },
      ],
    },
    {
      id: 3,
      descripcion: "Aceite de Oliva 250ml",
      marca: "Cocinero",
      rubro: "Envasados",
      precioVenta: 500,
      precioCosto: 300,
      tipoIva: "4%",
      stock: 7,
      stockMinimo: 5,
      proveedores: [
        { id: 1, razonSocial: "Distribuidora Pepe", cuit: "31-24865713-7" },
        { id: 3, razonSocial: "MaxiLauquen", cuit: "31-15487963-7" },
      ],
    },
  ],
  receta: [
    {
      id: 1,
      producto: 1,
      descripcion: "Empanada de Roquefort y Jamon",
      tiempoElaboracion: "35 min",
      cantidadProducto: 12,
      unidadMedida: "unidades",
      materiaPrima: [
        { nombre: "Muzzarella", cantidad: 100, unidadMedida: "gramos" },
        { nombre: "Jamon Cocido", cantidad: 150, unidadMedida: "gramos" },
        { nombre: "Queso Roquefort", cantidad: 200, unidadMedida: "gramos" },
      ],
    },
    {
      id: 2,
      producto: 3,
      descripcion: "Canastita de Caprese",
      tiempoElaboracion: "30 min",
      cantidadProducto: 12,
      unidadMedida: "unidades",
      materiaPrima: [
        { nombre: "Muzzarella", cantidad: 150, unidadMedida: "gramos" },
        { nombre: "Queso Rallado", cantidad: 150, unidadMedida: "gramos" },
        { nombre: "Queso Por Salut", cantidad: 150, unidadMedida: "gramos" },
        { nombre: "Tomate", cantidad: 300, unidadMedida: "gramos" },
        { nombre: "Albhaca Fresca", cantidad: 1, unidadMedida: "unidades" },
      ],
    },
    {
      id: 3,
      producto: 2,
      descripcion: "Empanada de Carne",
      tiempoElaboracion: "40 min",
      cantidadProducto: 12,
      unidadMedida: "unidades",
      materiaPrima: [
        { nombre: "Carne Picada", cantidad: 500, unidadMedida: "gramos" },
        { nombre: "Cebolla", cantidad: 2, unidadMedida: "unidades" },
        { nombre: "Dientes de Ajo", cantidad: 2, unidadMedida: "unidades" },
        { nombre: "Tomate", cantidad: 1, unidadMedida: "unidades" },
        { nombre: "Albhaca Fresca", cantidad: 1, unidadMedida: "unidades" },
        { nombre: "Puré de Tomate", cantidad: 2, unidadMedida: "cucharadas" },
        { nombre: "Aceitunas", cantidad: 5, unidadMedida: "unidades" },
      ],
    },
  ],
  ordenCompra: [
    {
      id: 1,
      fecha: "24/05/2022",
      hora: "10:00",
      proveedor: "Juan Cortes",
      encargado: "Federico Franchini",
      terminoEntrega: "Entrega en local y pago en efectivo",
      montoTotal: 14876,
      observaciones: "",
      productos: [
        {
          materiaPrima: null,
          producto: "Vino Tinto Benjamin",
          cantidad: 10,
          unidadMedida: "unidades",
          costoUnitario: 718,
          importe: 7180,
        },
        {
          materiaPrima: "Muzarella",
          producto: null,
          cantidad: 5,
          unidadMedida: "kilogramos",
          costoUnitario: 1000,
          importe: 5000,
        },
        {
          materiaPrima: "Brocoli x kg",
          producto: null,
          cantidad: "4",
          unidadMedida: "kilogramos",
          costoUnitario: 674,
          importe: 2696,
        },
      ],
    },
    {
      id: 2,
      fecha: "24/06/2022",
      hora: "17:00",
      proveedor: "Pedro Díaz",
      encargado: "Federico Franchini",
      terminoEntrega: "Entrega en local y pago en efectivo",
      montoTotal: 7530,
      observaciones: "",
      productos: [
        {
          materiaPrima: null,
          producto: "Aceite de Oliva 250ml",
          cantidad: 6,
          unidadMedida: "unidades",
          costoUnitario: 530,
          importe: 3180,
        },
        {
          materiaPrima: "Morcilla x kg",
          producto: null,
          cantidad: 3,
          unidadMedida: "kilogramos",
          costoUnitario: 700,
          importe: 2100,
        },
        {
          materiaPrima: "Queso Roquefort x kg",
          producto: null,
          cantidad: 1.5,
          unidadMedida: "kilogramos",
          costoUnitario: 1500,
          importe: 2250,
        },
      ],
    },
    {
      id: 3,
      fecha: "24/10/2022",
      hora: "12:00",
      proveedor: "Manuel Perez",
      encargado: "Federico Franchini",
      terminoEntrega: "Entrega en local y pago en efectivo",
      montoTotal: 8650,
      observaciones: "",
      productos: [
        {
          materiaPrima: null,
          producto: "Pickles 220g",
          cantidad: 5,
          unidadMedida: "unidades",
          costoUnitario: 250,
          importe: 1250,
        },
        {
          materiaPrima: "Jamon Crudo",
          producto: null,
          cantidad: 1.5,
          unidadMedida: "kilogramos",
          costoUnitario: 3600,
          importe: 5400,
        },
        {
          materiaPrima: "Cebolla x kg",
          producto: null,
          cantidad: 4,
          unidadMedida: "kilogramos",
          costoUnitario: 500,
          importe: 2000,
        },
      ],
    },
  ],
  facturaCompra: [
    {
      id: 1,
      tipoFactura: "B",
      nroFactura: "001/2022",
      fecha: new Date("2022-07-05T07:15").toLocaleString(),
      ordenCompra: 1,
      remitoProveedor: 1,
      proveedor: "Juan Perez",
      condicionVenta: "contado efectivo",
      montoTotal: 14876,
      observaciones: "",
      productos: [
        {
          materiaPrima: null,
          producto: "Vino Benjamin",
          cantidad: 10,
          unidadMedida: "unidades",
          costoUnitario: 718,
          importe: 7180,
        },
        {
          materiaPrima: "Muzarella",
          producto: null,
          cantidad: 5,
          unidadMedida: "kilogramos",
          costoUnitario: 1000,
          importe: 5000,
        },
        {
          materiaPrima: "Brocoli x kg",
          producto: null,
          cantidad: "4",
          unidadMedida: "kilogramos",
          costoUnitario: 674,
          importe: 2696,
        },
      ],
    },
    {
      id: 2,
      tipoFactura: "A",
      nroFactura: "002/2022",
      fecha: new Date("2022-01-29T11:05").toLocaleString(),
      ordenCompra: 3,
      remitoProveedor: 2,
      proveedor: "Juan Perez",
      condicionVenta: "contado efectivo",
      montoTotal: 10350,
      observaciones: "",
      productos: [
        {
          materiaPrima: "Muzarella",
          producto: null,
          cantidad: 5,
          unidadMedida: "kilogramos",
          costoUnitario: 1000,
          importe: 5000,
        },
        {
          materiaPrima: null,
          producto: "Pickles 220g",
          cantidad: 5,
          unidadMedida: "unidades",
          costoUnitario: 250,
          importe: 1250,
        },
        {
          materiaPrima: "Morcilla x kg",
          producto: null,
          cantidad: 3,
          unidadMedida: "kilogramos",
          costoUnitario: 700,
          importe: 2100,
        },
      ],
    },
    {
      id: 3,
      tipoFactura: "B",
      nroFactura: "003/2022",
      fecha: new Date("2022-11-17T11:05").toLocaleString(),
      ordenCompra: 2,
      remitoProveedor: 3,
      proveedor: "Juan Perez",
      condicionVenta: "contado efectivo",
      montoTotal: 12680,
      observaciones: "",
      productos: [
        {
          materiaPrima: null,
          producto: "Aceite de Oliva 250ml",
          cantidad: 6,
          unidadMedida: "unidades",
          costoUnitario: 530,
          importe: 3180,
        },
        {
          materiaPrima: "Morcilla x kg",
          producto: null,
          cantidad: 3,
          unidadMedida: "kilogramos",
          costoUnitario: 700,
          importe: 2100,
        },
        {
          materiaPrima: "Jamon Crudo",
          producto: null,
          cantidad: 1.5,
          unidadMedida: "kilogramos",
          costoUnitario: 3600,
          importe: 5400,
        },
        {
          materiaPrima: "Cebolla x kg",
          producto: null,
          cantidad: 4,
          unidadMedida: "kilogramos",
          costoUnitario: 500,
          importe: 2000,
        },
      ],
    },
  ],
  remitoProveedor: [
    {
      id: 1,
      fecha: "27/05/2022",
      hora: "11:00",
      proveedor: "Juan Perez",
      montoTotal: 14876,
      condicionVenta: "contado efectivo",
      observaciones: "",
      productos: [
        {
          materiaPrima: null,
          producto: "Vino Benjamin",
          cantidad: 10,
          unidadMedida: "unidades",
          costoUnitario: 718,
          importe: 7180,
        },
        {
          materiaPrima: "Muzarella",
          producto: null,
          cantidad: 5,
          unidadMedida: "kilogramos",
          costoUnitario: 1000,
          importe: 5000,
        },
        {
          materiaPrima: "Brocoli x kg",
          producto: null,
          cantidad: "4",
          unidadMedida: "kilogramos",
          costoUnitario: 674,
          importe: 2696,
        },
      ],
    },
    {
      id: 2,
      fecha: "18/07/2022",
      hora: "16:00",
      proveedor: "Esteban García",
      montoTotal: 10350,
      condicionVenta: "contado efectivo",
      observaciones: "",
      productos: [
        {
          materiaPrima: "Muzarella",
          producto: null,
          cantidad: 5,
          unidadMedida: "kilogramos",
          costoUnitario: 1000,
          importe: 5000,
        },
        {
          materiaPrima: null,
          producto: "Pickles 220g",
          cantidad: 5,
          unidadMedida: "unidades",
          costoUnitario: 250,
          importe: 1250,
        },
        {
          materiaPrima: "Morcilla x kg",
          producto: null,
          cantidad: 3,
          unidadMedida: "kilogramos",
          costoUnitario: 700,
          importe: 2100,
        },
      ],
    },
    {
      id: 3,
      fecha: "19/08/2022",
      hora: "10:00",
      proveedor: "Julian Paez",
      montoTotal: 12680,
      condicionVenta: "contado efectivo",
      observaciones: "",
      productos: [
        {
          materiaPrima: null,
          producto: "Aceite de Oliva 250ml",
          cantidad: 6,
          unidadMedida: "unidades",
          costoUnitario: 530,
          importe: 3180,
        },
        {
          materiaPrima: "Morcilla x kg",
          producto: null,
          cantidad: 3,
          unidadMedida: "kilogramos",
          costoUnitario: 700,
          importe: 2100,
        },
        {
          materiaPrima: "Jamon Crudo",
          producto: null,
          cantidad: 1.5,
          unidadMedida: "kilogramos",
          costoUnitario: 3600,
          importe: 5400,
        },
        {
          materiaPrima: "Cebolla x kg",
          producto: null,
          cantidad: 4,
          unidadMedida: "kilogramos",
          costoUnitario: 500,
          importe: 2000,
        },
      ],
    },
  ],
  rubro: [
    {
      id: 1,
      descripcion: "Comidas",
      porcentajeAumento: 2,
      ultimoAumento: "22/10/2022",
    },
    {
      id: 2,
      descripcion: "Bebidas",
      porcentajeAumento: 5,
      ultimoAumento: "30/10/2022",
    },
    {
      id: 3,
      descripcion: "Envasados",
      porcentajeAumento: 3,
      ultimoAumento: "17/10/2022",
    },
  ],
  marca: [
    {
      id: 1,
      nombre: "Trapiche",
      porcentajeAumento: 2,
      ultimoAumento: "22/10/2022",
    },
    {
      id: 2,
      nombre: "Cocinero",
      porcentajeAumento: 5,
      ultimoAumento: "30/10/2022",
    },
    {
      id: 3,
      nombre: "Don Silvestre",
      porcentajeAumento: 5,
      ultimoAumento: "30/10/2022",
    },
  ],
  producto: [
    {
      id: 1,
      descripcion: "Empanada de Roquefort y Jamon",
      marca: null,
      rubro: "Comidas",
      precioVenta: 150,
      precioCosto: null,
      tipoIva: "4%",
      stock: 20,
      stockMinimo: 10,
      proveedores: null,
    },
    {
      id: 2,
      descripcion: "Vino Tinto Malbec",
      marca: "Trapiche",
      rubro: "Bebidas",
      precioVenta: 1200,
      precioCosto: 700,
      tipoIva: "21%",
      stock: 5,
      stockMinimo: 2,
      proveedores: [
        { id: 1, razonSocial: "Codeana S.A", cuit: "31-35665513-7" },
      ],
    },
    {
      id: 3,
      descripcion: "Aceite de Oliva 250ml",
      marca: "Cocinero",
      rubro: "Envasados",
      precioVenta: 500,
      precioCosto: 300,
      tipoIva: "4%",
      stock: 7,
      stockMinimo: 5,
      proveedores: [
        { id: 1, razonSocial: "Distribuidora Pepe", cuit: "31-24865713-7" },
        { id: 3, razonSocial: "MaxiLauquen", cuit: "31-15487963-7" },
      ],
    },
  ],
  receta: [
    {
      id: 1,
      producto: 1,
      descripcion: "Empanada de Roquefort y Jamon",
      tiempoElaboracion: "35 min",
      cantidadProducto: 12,
      unidadMedida: "unidades",
      materiaPrima: [
        { nombre: "Muzzarella", cantidad: 100, unidadMedida: "gramos" },
        { nombre: "Jamon Cocido", cantidad: 150, unidadMedida: "gramos" },
        { nombre: "Queso Roquefort", cantidad: 200, unidadMedida: "gramos" },
      ],
    },
    {
      id: 2,
      producto: 3,
      descripcion: "Canastita de Caprese",
      tiempoElaboracion: "30 min",
      cantidadProducto: 12,
      unidadMedida: "unidades",
      materiaPrima: [
        { nombre: "Muzzarella", cantidad: 150, unidadMedida: "gramos" },
        { nombre: "Queso Rallado", cantidad: 150, unidadMedida: "gramos" },
        { nombre: "Queso Por Salut", cantidad: 150, unidadMedida: "gramos" },
        { nombre: "Tomate", cantidad: 300, unidadMedida: "gramos" },
        { nombre: "Albhaca Fresca", cantidad: 1, unidadMedida: "unidades" },
      ],
    },
    {
      id: 3,
      producto: 2,
      descripcion: "Empanada de Carne",
      tiempoElaboracion: "40 min",
      cantidadProducto: 12,
      unidadMedida: "unidades",
      materiaPrima: [
        { nombre: "Carne Picada", cantidad: 500, unidadMedida: "gramos" },
        { nombre: "Cebolla", cantidad: 2, unidadMedida: "unidades" },
        { nombre: "Dientes de Ajo", cantidad: 2, unidadMedida: "unidades" },
        { nombre: "Tomate", cantidad: 1, unidadMedida: "unidades" },
        { nombre: "Albhaca Fresca", cantidad: 1, unidadMedida: "unidades" },
        { nombre: "Puré de Tomate", cantidad: 2, unidadMedida: "cucharadas" },
        { nombre: "Aceitunas", cantidad: 5, unidadMedida: "unidades" },
      ],
    },
  ],
  pedido: [
    {
      id: 1,
      cliente: "Carlos Zabala",
      delivery: "Pedro Ríos",
      encargado: "Marcos Ozamis",
      presupuesto: null,
      fechaPedido: "15/05/2022",
      horaPedido: "21:30",
      fechaEnvio: "15/05/2022",
      horaEnvio: "22:30",
      entregaDomicilio: true,
      costoEnvio: 200,
      razonSocialEntrega: "Juan Diaz",
      telefonoEntrega: "2392475869",
      calle: "Roca",
      altura: 855,
      depto: 1,
      tipoVenta: "minorista",
      estado: "en entrega",
      observaciones: "La casa tiene una reja negra.",
      montoTotal: 1380,
      productos: [
        {
          producto: "Empanada de Carne",
          cantidad: 5,
          unidadMedida: "unidades",
          precioUnitario: 120,
          importe: 600,
        },
        {
          producto: "Canastita de Queso y Cebolla",
          cantidad: 3,
          unidadMedida: "unidades",
          precioUnitario: 100,
          importe: 300,
        },
        {
          producto: "Empanada de Hongos",
          cantidad: 4,
          unidadMedida: "unidades",
          precioUnitario: 125,
          importe: 480,
        },
      ],
    },
    {
      id: 2,
      cliente: "Hernan Botte",
      delivery: null,
      encargado: "Vero Carrizo",
      presupuesto: null,
      fechaPedido: "23/06/2022",
      horaPedido: "22:15",
      fechaEnvio: "24/06/2022",
      horaEnvio: "12:00",
      entregaDomicilio: false,
      costoEnvio: 0,
      razonSocialEntrega: "Hernan Botte",
      telefonoEntrega: "2392789563",
      calle: "Rivadavia",
      altura: 285,
      depto: null,
      tipoVenta: "minorista",
      estado: "en proceso",
      observaciones: null,
      montoTotal: 2740,
      productos: [
        {
          producto: "Vino Malbec Benjamin x 750",
          cantidad: 1,
          unidadMedida: "unidades",
          precioUnitario: 700,
          importe: 700,
        },
        {
          producto: "Empanada de Jamon y Queso",
          cantidad: 6,
          unidadMedida: "unidad",
          precioUnitario: 100,
          importe: 600,
        },
        {
          producto: "Empanada de Carne",
          cantidad: 6,
          unidadMedida: "unidad",
          precioUnitario: 120,
          importe: 720,
        },
        {
          producto: "Canastita de Pollo y Brocoli",
          cantidad: 6,
          unidadMedida: "unidad",
          precioUnitario: 120,
          importe: 720,
        },
      ],
    },
    {
      id: 3,
      cliente: "Karina Gonzalez",
      delivery: null,
      encargado: "Marcos Ozamis",
      presupuesto: 2,
      fechaPedido: "04/07/2022",
      horaPedido: "13:00",
      fechaEnvio: "08/07/2022",
      horaEnvio: "10:00",
      entregaDomicilio: false,
      costoEnvio: 0,
      razonSocialEntrega: null,
      telefonoEntrega: null,
      calle: null,
      altura: null,
      depto: null,
      tipoVenta: "mayorista",
      estado: "lista para entrega",
      observaciones:
        "Pedido especial para cumpleaños. Envío a cargo del cliente.",
      montoTotal: 21160,
      productos: [
        {
          producto: "Vino Malbec Benjamin x 750",
          cantidad: 10,
          unidadMedida: "unidades",
          precioUnitario: 700,
          importe: 7000,
        },
        {
          producto: "Empanada de Jamon y Queso",
          cantidad: 36,
          unidadMedida: "unidad",
          precioUnitario: 110,
          importe: 3960,
        },
        {
          producto: "Empanada de Carne",
          cantidad: 36,
          unidadMedida: "unidad",
          precioUnitario: 120,
          importe: 4320,
        },
        {
          producto: "Canastita de Pollo y Brocoli",
          cantidad: 12,
          unidadMedida: "unidad",
          precioUnitario: 120,
          importe: 1440,
        },
        {
          producto: "Jamon y Roquefort",
          cantidad: 12,
          unidadMedida: "unidad",
          precioUnitario: 150,
          importe: 1800,
        },
        {
          producto: "Canastita de Humita",
          cantidad: 24,
          unidadMedida: "unidad",
          precioUnitario: 110,
          importe: 2640,
        },
      ],
    },
  ],
  presupuesto: [
    {
      id: 1,
      fechaEmision: "10/05/2020",
      horaEmision: "12:10",
      fechaEvento: "30/05/2020",
      horaEvento: "",
      validez: 10,
      cliente: "Juan Arias",
      subTotal: 10800,
      descuento: 1080,
      costoTotal: 9720,
      observaciones: "",
      productos: [
        {
          producto: "Empanada de Carne",
          cantidad: 36,
          unidadMedida: "unidades",
          precioUnitario: 120,
          importe: 4320,
        },
        {
          producto: "Empanada de Jamon y Queso",
          cantidad: 36,
          unidadMedida: "unidades",
          precioUnitario: 100,
          importe: 3600,
        },
        {
          producto: "Canastita de Humita",
          cantidad: 24,
          unidadMedida: "unidades",
          precioUnitario: 120,
          importe: 2880,
        },
      ],
    },
    {
      id: 2,
      fechaEmision: "04/06/2021",
      horaEmision: "12:10",
      fechaEvento: "04/07/2020",
      horaEvento: "",
      validez: 7,
      cliente: "Damian Gonzales",
      subTotal: 9280,
      descuento: 0,
      costoTotal: 9280,
      observaciones: "",
      productos: [
        {
          producto: "Empanada de Jamon y Queso",
          cantidad: 24,
          unidadMedida: "unidades",
          precioUnitario: 100,
          importe: 2400,
        },
        {
          producto: "Empanada de Carne ",
          cantidad: 24,
          unidadMedida: "unidades",
          precioUnitario: 120,
          importe: 2880,
        },
        {
          producto: "Vino Malbec Benjamin",
          cantidad: 5,
          unidadMedida: "unidades",
          precioUnitario: 800,
          importe: 4000,
        },
      ],
    },
  ],
  reclamo: [
    {
      id: 1,
      fecha: "12/10/2018",
      pedido: 1,
      descripcion: "Faltaron dos empanadas de hongos",
    },
    {
      id: 2,
      fecha: "12/10/2020",
      pedido: 2,
      descripcion: "Las canastitas de brocoli llegaron frias",
    },
    {
      id: 3,
      fecha: "12/10/2020",
      pedido: 3,
      descripcion: "El cliente pidió empanadas de atun y no se le enviaron",
    },
  ],
  comprobanteVenta: [
    {
      id: 1,
      tipoFactura: "B",
      nroFactura: "001/2022",
      fecha: "15/05/2022",
      hora: "22:00",
      pedido: 1,
      montoTotal: 1380,
      observaciones: "",
      productos: [
        {
          producto: "Empanada de Carne",
          cantidad: 5,
          unidadMedida: "unidades",
          precioUnitario: 120,
          importe: 600,
        },
        {
          producto: "Canastita de Queso y Cebolla",
          cantidad: 3,
          unidadMedida: "unidades",
          precioUnitario: 100,
          importe: 300,
        },
        {
          producto: "Empanada de Hongos",
          cantidad: 4,
          unidadMedida: "unidades",
          precioUnitario: 125,
          importe: 480,
        },
      ],
    },
    {
      id: 2,
      tipoFactura: "A",
      nroFactura: "002/2022",
      fecha: "08/07/2022",
      hora: "10:05",
      pedido: 3,
      montoTotal: 21160,
      observaciones: "",
      productos: [
        {
          producto: "Vino Malbec Benjamin x 750",
          cantidad: 10,
          unidadMedida: "unidades",
          precioUnitario: 700,
          importe: 7000,
        },
        {
          producto: "Empanada de Jamon y Queso",
          cantidad: 36,
          unidadMedida: "unidad",
          precioUnitario: 110,
          importe: 3960,
        },
        {
          producto: "Empanada de Carne",
          cantidad: 36,
          unidadMedida: "unidad",
          precioUnitario: 120,
          importe: 4320,
        },
        {
          producto: "Canastita de Pollo y Brocoli",
          cantidad: 12,
          unidadMedida: "unidad",
          precioUnitario: 120,
          importe: 1440,
        },
        {
          producto: "Jamon y Roquefort",
          cantidad: 12,
          unidadMedida: "unidad",
          precioUnitario: 150,
          importe: 1800,
        },
        {
          producto: "Canastita de Humita",
          cantidad: 24,
          unidadMedida: "unidad",
          precioUnitario: 110,
          importe: 2640,
        },
      ],
    },
    {
      id: 3,
      tipoFactura: "B",
      nroFactura: "003/2022",
      fecha: "05/10/2022",
      hora: "21:00",
      pedido: 2,
      montoTotal: 1380,
      observaciones: "",
      productos: [
        {
          producto: "Empanada de Carne",
          cantidad: 6,
          unidadMedida: "unidades",
          precioUnitario: 120,
          importe: 720,
        },
        {
          producto: "Empanada de Jamon y Queso",
          cantidad: 6,
          unidadMedida: "unidades",
          precioUnitario: 110,
          importe: 660,
        },
      ],
    },
  ],
  remitoEntrega: [
    {
      id: 1,
      fecha: "15/05/2022",
      hora: "22:00",
      pedido: 1,
      montoTotal: 1380,
      condicionVenta: "contado efectivo",
      observaciones: "",
      productos: [
        {
          producto: "Empanada de Carne",
          cantidad: 5,
          unidadMedida: "unidades",
          precioUnitario: 120,
          importe: 600,
        },
        {
          producto: "Canastita de Queso y Cebolla",
          cantidad: 3,
          unidadMedida: "unidades",
          precioUnitario: 100,
          importe: 300,
        },
        {
          producto: "Empanada de Hongos",
          cantidad: 4,
          unidadMedida: "unidades",
          precioUnitario: 125,
          importe: 480,
        },
      ],
    },
    {
      id: 2,
      fecha: "08/07/2022",
      hora: "10:05",
      pedido: 3,
      montoTotal: 21160,
      condicionVenta: "contado efectivo",
      observaciones: "",
      productos: [
        {
          producto: "Vino Malbec Benjamin x 750",
          cantidad: 10,
          unidadMedida: "unidades",
          precioUnitario: 700,
          importe: 7000,
        },
        {
          producto: "Empanada de Jamon y Queso",
          cantidad: 36,
          unidadMedida: "unidad",
          precioUnitario: 110,
          importe: 3960,
        },
        {
          producto: "Empanada de Carne",
          cantidad: 36,
          unidadMedida: "unidad",
          precioUnitario: 120,
          importe: 4320,
        },
        {
          producto: "Canastita de Pollo y Brocoli",
          cantidad: 12,
          unidadMedida: "unidad",
          precioUnitario: 120,
          importe: 1440,
        },
        {
          producto: "Jamon y Roquefort",
          cantidad: 12,
          unidadMedida: "unidad",
          precioUnitario: 150,
          importe: 1800,
        },
        {
          producto: "Canastita de Humita",
          cantidad: 24,
          unidadMedida: "unidad",
          precioUnitario: 110,
          importe: 2640,
        },
      ],
    },
    {
      id: 3,
      fecha: "05/10/2022",
      hora: "21:00",
      pedido: 2,
      montoTotal: 1380,
      condicionVenta: "contado efectivo",
      observaciones: "",
      productos: [
        {
          producto: "Empanada de Carne",
          cantidad: 6,
          unidadMedida: "unidades",
          precioUnitario: 120,
          importe: 720,
        },
        {
          producto: "Empanada de Jamon y Queso",
          cantidad: 6,
          unidadMedida: "unidades",
          precioUnitario: 110,
          importe: 660,
        },
      ],
    },
  ],
  calle: [
    {
      id: 1,
      nombre: "San Martin",
      localidad: "Rivadavia",
    },
    {
      id: 2,
      nombre: "San Martin",
      localidad: "Trenque Lauquen",
    },
    {
      id: 3,
      nombre: "Sarmiento",
      localidad: "Teodolina",
    },
    {
      id: 4,
      nombre: "Suipacha",
      localidad: "Villa Mercedes",
    },
    {
      id: 5,
      nombre: "Uruguay",
      localidad: "Zapala",
    },
  ],
  localidad: [
    {
      id: 1,
      nombre: "Trenque Lauquen",
      codigoPostal: 6400,
      provincia: "Buenos Aires",
    },
    {
      id: 2,
      nombre: "Rivadavia",
      codigoPostal: 6237,
      provincia: "Buenos Aires",
    },
    {
      id: 3,
      nombre: "Rivadavia",
      codigoPostal: 5567,
      provincia: "Mendoza",
    },
    {
      id: 4,
      nombre: "Quemu Quemu",
      codigoPostal: 6333,
      provincia: "La Pampa",
    },
  ],
  provincia: [
    {
      id: 1,
      nombre: "Buenos Aires",
    },
    {
      id: 2,
      nombre: "Mendoza",
    },
    {
      id: 3,
      nombre: "Tucuman",
    },
    {
      id: 4,
      nombre: "Neuquen",
    },
    {
      id: 5,
      nombre: "La Pampa",
    },
  ],
  unidadMedida: [
    {
      id: 1,
      descripcion: "unidades",
    },
    {
      id: 2,
      descripcion: "gramos",
    },
    {
      id: 3,
      descripcion: "kilogramos",
    },
    {
      id: 4,
      descripcion: "cucharadas",
    },
  ],
  tipoDocumento: [
    {
      id: 1,
      nombre: "dni",
    },
    {
      id: 2,
      nombre: "cuil",
    },
    {
      id: 3,
      nombre: "cuit",
    },
    {
      id: 4,
      nombre: "pasaporte",
    },
    {
      id: 5,
      nombre: "libreta civica",
    },
    {
      id: 6,
      nombre: "libreta de enrolamiento",
    },
  ],
  tipoIVA: [
    {
      id: 1,
      descripcion: "tasa general",
      abreviatura: "21%",
    },
    {
      id: 2,
      descripcion: "bienes de capital y primera necesidad",
      abreviatura: "10,5%",
    },
    {
      id: 3,
      descripcion: "energía electrica y telecomunicaciones",
      abreviatura: "27%",
    },
  ],
  formaPago: [
    {
      id: 1,
      descripcion: "contado efectivo",
    },
    {
      id: 2,
      descripcion: "contado tarjeta debito",
    },
    {
      id: 3,
      descripcion: "cuotas tarjeta credito",
    },
    {
      id: 4,
      descripcion: "mercado pago",
    },
  ],
  ordenProduccion: [
    {
      id: 1,
      fecha: "15/05/2022",
      hora: "21:40",
      pedido: 1,
      encargado: "Manuel Martinez",
      productos: [
        {
          producto: "Empanada de Carne",
          cantidad: 5,
          unidadMedida: "unidades",
        },
        {
          producto: "Canastita de Queso y Cebolla",
          cantidad: 3,
          unidadMedida: "unidades",
        },
        {
          producto: "Empanada de Hongos",
          cantidad: 4,
          unidadMedida: "unidades",
        },
      ],
    },
    {
      id: 2,
      fecha: "21/06/2022",
      hora: "11:00",
      pedido: null,
      encargado: "Manuel Martinez",
      productos: [
        {
          producto: "Empanada de Carne",
          cantidad: 36,
          unidadMedida: "unidades",
        },
        {
          producto: "Empanada de Jamon y Queso",
          cantidad: 48,
          unidadMedida: "unidades",
        },
        {
          producto: "Empanada de Roquefort y Jamon",
          cantidad: 24,
          unidadMedida: "unidades",
        },
        {
          producto: "Canastita de Pollo y Brocoli",
          cantidad: 24,
          unidadMedida: "unidades",
        },
      ],
    },
  ],
  tipoResponsable: [
    {
      id: 1,
      descripcion: "IVA Responsable Inscripto",
    },
    {
      id: 2,
      descripcion: "IVA Responsable no Inscripto",
    },
    {
      id: 3,
      descripcion: "Consumidor Final",
    },
    {
      id: 4,
      descripcion: "Responsable Monotributo",
    },
    {
      id: 5,
      descripcion: "Proveedor del Exterior",
    },
    {
      id: 6,
      descripcion: "Cliente del Exterior",
    },
    {
      id: 7,
      descripcion: "Pequeño Contribuyente Eventual",
    },
    {
      id: 8,
      descripcion: "Monotributista Social",
    },
  ],
  materiaPrima: [
    {
      id: 1,
      descripcion: "Muzarella",
      fechaIngreso: "10/02/2017",
      stockDisponible: 5,
      stockMinimo: 4,
      unidadMedidad: "kilogramos",
      precioCosto: 1000,
    },
    {
      id: 2,
      descripcion: "Jamon Cocido",
      fechaIngreso: "15/09/2018",
      stockDisponible: 2,
      stockMinimo: 1,
      unidadMedidad: "kilogramos",
      precioCosto: 3600,
    },
    {
      id: 3,
      descripcion: "Brocoli",
      fechaIngreso: "13/06/2019",
      stockDisponible: 2,
      stockMinimo: 1,
      unidadMedidad: "kilogramos",
      precioCosto: 674,
    },
    {
      id: 4,
      descripcion: "Tomate",
      fechaIngreso: "2/10/2021",
      stockDisponible: 5,
      stockMinimo: 5,
      unidadMedidad: "kilogramos",
      precioCosto: 420,
    },
    {
      id: 5,
      descripcion: "Carne Picada",
      fechaIngreso: "01/11/2022",
      stockDisponible: 5,
      stockMinimo: 3,
      unidadMedida: "kilogramos",
      precioCosto: 800,
    },
  ],
  cliente: [
    {
      id: 1,
      razonSocial: "Carlos Zabala",
      tipoDocumento: "dni",
      nroDocumento: "23798088",
      calle: "San Martin",
      altura: 425,
      depto: "1B",
      fechaNacimiento: "10/03/1973",
      telefono: "02392552847",
      mail: "ZabalaC@gmail.com",
      tipoResponsable: "Consumidor Final",
    },
    {
      id: 2,
      razonSocial: "Cargil S.A",
      tipoDocumento: "cuit",
      nroDocumento: "30506792165",
      calle: "Ruta 5 Km 446",
      altura: null,
      depto: null,
      fechaNacimiento: null,
      telefono: "02392423210",
      mail: "administracion@cargil.com",
      tipoResponsable: "IVA Responsable Inscripto",
    },
    {
      id: 3,
      razonSocial: "Diego Paez",
      tipoDocumento: "dni",
      nroDocumento: "27055221",
      calle: "Sarmiento",
      altura: 120,
      depto: null,
      fechaNacimiento: "12/10/1980",
      telefono: "02396232654",
      mail: "diego.paez@hotmail.com",
      tipoResponsable: "Responsable Monotributo",
    },
  ],
  delivery: [
    {
      id: 1,
      nombreApellido: "Pedro Rios",
      tipoDocumento: "dni",
      nroDocumento: "23798088",
      calle: "Pasteur",
      altura: 580,
      depto: "1",
      telefono: "02392552847",
      mail: "rios.p223@gmail.com",
      vehiculo: "Honda Titan 150",
      patente: "WPQ325",
      numeroHabilitacion: "25463669",
      vencimientoHabilitacion: "15/10/2014",
    },
    {
      id: 2,
      nombreApellido: "Marcos Zarria",
      tipoDocumento: "dni",
      nroDocumento: "24986152",
      calle: "Almafuerte",
      altura: 225,
      depto: null,
      telefono: "02392441326",
      mail: "marcoszarria0610@hotmail.com",
      vehiculo: "Zanella ZB 110",
      patente: "CQR864",
      numeroHabilitacion: "23659877",
      vencimientoHabilitacion: "20/03/2016",
    },
    {
      id: 3,
      nombreApellido: "Juan Gonzalez",
      tipoDocumento: "dni",
      nroDocumento: "23456983",
      calle: "Tala",
      altura: 500,
      depto: null,
      telefono: "02337765412",
      mail: "gonzalez30@gmail.com",
      vehiculo: "Motomel 110",
      patente: "ASC225",
      numeroHabilitacion: "25587496",
      vencimientoHabilitacion: "12/10/2017",
    },
  ],
  personal: [
    {
      id: 1,
      nombreApellido: "Marcos Ozamis",
      tipoDocumento: "dni",
      nroDocumento: "23798088",
      calle: "Castelli",
      altura: 420,
      depto: null,
      telefono: "02392094926",
      mail: "ozamis.marcos@gmail.com",
      puesto: "Administrativo",
      sueldo: 800000,
      nivel: 1,
    },
    {
      id: 2,
      nombreApellido: "Federico Franchini",
      tipoDocumento: "dni",
      nroDocumento: "25641075",
      calle: "Villegas",
      altura: 411,
      depto: "4C",
      telefono: "02337415293",
      mail: "franchinifede@yahoo.com.ar",
      puesto: "Encargado de Compras",
      sueldo: 60000,
      nivel: 2,
    },
    {
      id: 3,
      nombreApellido: "Manuel Martinez",
      tipoDocumento: "dni",
      nroDocumento: "26048580E",
      calle: "Tala",
      altura: 500,
      depto: null,
      telefono: "02354452100",
      mail: "manuelmartinez@gmail.com",
      puesto: "Encargado de Produccion",
      sueldo: 45000,
      nivel: 3,
    },
  ],
  proveedor: [
    /* Juan Cortes, Pedro Díaz, Manuel Perez */
    {
      id: 1,
      razonSocial: "Juan Cortes",
      tipoDocumento: "cuit",
      nroDocumento: "34139854170",
      calle: "Ameghino",
      altura: 350,
      depto: null,
      telefono: "02392440746",
      mail: "cortesJuan@gmail.com",
      inicioActividad: "",
      ingresosBrutos: "",
      web: "carniceriadeloeste.com.ar",
    },
    {
      id: 2,
      razonSocial: "Pedro Díaz",
      tipoDocumento: "cuit",
      nroDocumento: "24988225556",
      calle: "Regimiento 3 de Caballeria",
      altura: 500,
      depto: null,
      telefono: "02392623052",
      mail: "diaz.pedro@codeana.com",
      inicioActividad: "",
      ingresosBrutos: "",
      web: "codeana.com.ar",
    },
    {
      id: 3,
      razonSocial: "Manuel Perez",
      tipoDocumento: "cuit",
      nroDocumento: "30365473443",
      calle: "Presidente Juan Domingo Peron",
      altura: 1237,
      depto: null,
      telefono: "02392974718",
      mail: "perez_manuel@gmail.com",
      inicioActividad: "",
      ingresosBrutos: "",
      web: "ditribuidoraperez.com.ar",
    },
  ],
};
