export default {
  rubros: [
    {
      id: 1,
      descripcion: "Comidas",
    },
    {
      id: 2,
      descripcion: "Bebidas",
    },
    {
      id: 3,
      descripcion: "Envasados",
    },
  ],
  marcas: [
    {
      id: 1,
      nombre: "Trapiche",
    },
    {
      id: 2,
      nombre: "Cocinero",
    },
    {
      id: 3,
      nombre: "Don Silvestre",
    },
  ],
  productos: [
    {
      id: 1,
      descripcion: "Empanada de Roquefort y Jamon",
      marca: null,
      rubro: "Comidas",
      precioVenta: 150,
      precioCosto: null,
      tipoIva: "4%",
      stock: 20,
      stockMinimo: 10,
      proveedores: null,
    },
    {
      id: 2,
      descripcion: "Vino Tinto Malbec",
      marca: "Trapiche",
      rubro: "Bebidas",
      precioVenta: 1200,
      precioCosto: 700,
      tipoIva: "21%",
      stock: 5,
      stockMinimo: 2,
      proveedores: [
        { id: 1, razonSocial: "Codeana S.A", cuit: "31-35665513-7" },
      ], 
    },
    {
      id: 3,
      descripcion: "Aceite de Oliva 250ml",
      marca: "Cocinero",
      rubro: "Envasados",
      precioVenta: 500,
      precioCosto: 300,
      tipoIva: "4%",
      stock: 7,
      stockMinimo: 5,
      proveedores: [
        { id: 1, razonSocial: "Distribuidora Pepe", cuit: "31-24865713-7" },
        { id: 3, razonSocial: "MaxiLauquen", cuit: "31-15487963-7" },
      ],
    },
  ],
  recetas: [
    {
      id: 1,
      producto: 1,
      descripcion: "Empanada de Roquefort y Jamon",
      tiempoElaboracion: "35 min",
      cantidadProducto: 12,
      unidadMedida: "unidades",
      materiaPrima: [
        { nombre: "Muzzarella", cantidad: 100, unidadMedida: "gramos" },
        { nombre: "Jamon Cocido", cantidad: 150, unidadMedida: "gramos" },
        { nombre: "Queso Roquefort", cantidad: 200, unidadMedida: "gramos" },
      ],
    },
    {
      id: 2,
      producto: 5,
      descripcion: "Canastita de Caprese",
      tiempoElaboracion: "30 min",
      cantidadProducto: 12,
      unidadMedida: "unidades",
      materiaPrima: [
        { nombre: "Muzzarella", cantidad: 150, unidadMedida: "gramos" },
        { nombre: "Queso Rallado", cantidad: 150, unidadMedida: "gramos" },
        { nombre: "Queso Por Salut", cantidad: 150, unidadMedida: "gramos" },
        { nombre: "Tomate", cantidad: 300, unidadMedida: "gramos" },
        { nombre: "Albhaca Fresca", cantidad: 1, unidadMedida: "unidades" },
      ],
    },
    {
      id: 3,
      producto: 8,
      descripcion: "Empanada de Carne",
      tiempoElaboracion: "40 min",
      cantidadProducto: 12,
      unidadMedida: "unidades",
      materiaPrima: [
        { nombre: "Carne Picada", cantidad: 500, unidadMedida: "gramos" },
        { nombre: "Cebolla", cantidad: 2, unidadMedida: "unidades" },
        { nombre: "Dientes de Ajo", cantidad: 2, unidadMedida: "unidades" },
        { nombre: "Tomate", cantidad: 1, unidadMedida: "unidades" },
        { nombre: "Albhaca Fresca", cantidad: 1, unidadMedida: "unidades" },
        { nombre: "Puré de Tomate", cantidad: 2, unidadMedida: "cucharadas" },
        { nombre: "Aceitunas", cantidad: 5, unidadMedida: "unidades" },
      ],
    },
  ],
};
